### ISSUE TITLE
Webcomponent version

### ISSUE THREAD

**Issue by Mateiadrielrafael** [danevans/lit-router#2]
No hate,but the tagged template syntax is kinda ugly for this kind of thing, ive juat made this: 
![lit-router](https://user-images.githubusercontent.com/39400800/57674035-b3452a00-7626-11e9-8c81-ef03c6b70bfc.png)

If i were to make a new webcomppnents branch, will it be ok i didnt use this particular library for the under the hood router? (I tried this but the lack of ts support killed me)

**Comment by danevans** [comment]
I disagree. I think tagged template literals look good and I don't like the web component version you showed. The only thing this project is for is creating a tagged template-based router. I don't think it makes sense to make a branch with a component syntax. This is what the `lit-` in `lit-router` is for short for: literals. So in your component one you probably wouldn't even call it `lit-router` anymore.

Why don't you just create your own project?

**Comment by Mateiadrielrafael** [comment]
Well, i actually used your thing under the hood so thats why I thought it belongs here somewhere. 
    Thanks for the reply and good luck on your future projects!
